spring:
    thymeleaf:
        mode: HTML
server:
    servlet:
        context-path: /
    compression:
        enabled: true
        mime-types:
            - text/css
            - text/html
            - application/javascript
            - application/json
