spring:
    profiles:
        active: devel
    thymeleaf:
        mode: HTML
        enable-spring-el-compiler: true
    messages:
        basename: messages
        encoding: UTF-8
    servlet:
        multipart:
            resolve-lazily: true
            max-file-size: 2MB
            max-request-size: 20MB
server:
    servlet:
        context-path: /
    error:
        path: /error
    compression:
        enabled: true
        mime-types:
            - text/css
            - text/html
            - application/javascript
            - application/json

---
spring:
    profiles: devel
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
        driverClassName: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            # see http://localhost:8080/h2-console
            #  JDBC URL: jdbc:h2:mem:example
            enabled: true
    flyway:
        locations: classpath:/db/migration,classpath:/db/testdata
doma:
    dialect: h2
server:
    port: 8080
setting:
    siteUrl: http://localhost:8080/

---
spring:
    profiles: production
    datasource:
        # see https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku#connecting-to-a-database
        # heroku config
        url: "@see Procfile:--spring.datasouce.url"
        driverClassName: org.postgresql.Driver
doma:
    dialect: POSTGRES
    exception-sql-log-type: NONE
setting:
    siteUrl: https://example.com/
